#pragma once

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U 
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

#define SPLIT_WATCHDOG_ENABLE 
#define SPLIT_WATCHDOG_TIMEOUT 3000
#define SPLIT_USB_DETECT 
#define SPLIT_USB_TIMEOUT_POLL 10 